export const MODALS = {
  REPOST_SUCCESS: 'REPOST_SUCCESS',
  INVITE_TO_REPOST: 'INVITE_TO_REPOST',
  NOTIFICATIONS_ARE_DISABLED: 'NOTIFICATIONS_ARE_DISABLED',
  NOTIFICATIONS_ARE_ENABLED: 'NOTIFICATIONS_ARE_ENABLED',
  INVITE_TO_ENABLE_NOTIFICATIONS: 'INVITE_TO_ENABLE_NOTIFICATIONS',
  VOTING_IS_ENDED: 'VOTING_IS_ENDED',
};
