import ROLES from './roles';

import Albicy from '../Images/Albicy_240x240.jpg';
import Voronov from '../Images/Voron_240x240.jpg';
import Ponkrashov from '../Images/Ponkr_240x240.jpg';
import Renfro from '../Images/Renf_240x240.jpg';
import Khvorostov from '../Images/Khvo_240x240.jpg';
import Hollinz from '../Images/Holli_240x240.jpg';
import Abromajtiz from '../Images/Abro_240x240.jpg';
import Zubkov from '../Images/Zub_240x240.jpg';
import Ponitka from '../Images/Poni_240x240.jpg';
import Thomas from '../Images/Tom_240x240.jpg';
import Trushkin from '../Images/Tru_240x240.jpg';
import Iverson from '../Images/Iver_240x240.jpg';
import Ayon from '../Images/Ayon_240x240.jpg';
import Pushkov from '../Images/Pukh_240x240.jpg';

const players = [
  {
    id: 1,
    name: 'Эндрю Альбиси',
    number: 6,
    role: ROLES.GUARD,
    age: 29,
    height: 178,
    weight: 77,
    country: 'Франция',
    photo: Albicy,
    twitter: 'andrewalbicy',
    instagram: 'andrewalbicy',
    images: [],
  },
  {
    id: 2,
    name: 'Евгений Воронов',
    number: 18,
    role: ROLES.GUARD,
    age: 33,
    height: 194,
    weight: 95,
    country: 'Россия',
    photo: Voronov,
    twitter: '',
    instagram: 'evgeny.voronov',
    images: [],
  },
  {
    id: 3,
    name: 'Антон Понкрашов',
    number: 7,
    role: ROLES.GUARD,
    age: 33,
    height: 200,
    weight: 93,
    country: 'Россия',
    photo: Ponkrashov,
    twitter: 'ponkrash',
    instagram: 'antonponkrashov',
    images: [],
  },
  {
    id: 4,
    name: 'Алекс Ренфро',
    number: 12,
    role: ROLES.GUARD,
    age: 33,
    height: 191,
    weight: 80,
    country: 'США',
    photo: Renfro,
    twitter: 'lilaI523',
    instagram: 'renfroe32alex',
    images: [],
  },
  {
    id: 5,
    name: 'Дмитрий Хвостов',
    number: 13,
    role: ROLES.GUARD,
    age: 30,
    height: 190,
    weight: 84,
    country: 'Россия',
    photo: Khvorostov,
    twitter: '',
    instagram: 'xvost',
    images: [],
  },
  {
    id: 6,
    name: 'Остин Холлинз',
    number: 9,
    role: ROLES.GUARD,
    age: 27,
    height: 193,
    weight: 86,
    country: 'США',
    photo: Hollinz,
    twitter: 'aHolli_20',
    instagram: 'aholli_20',
    images: [],
  },
  {
    id: 7,
    name: 'Тим Абромайтис',
    number: 21,
    role: ROLES.FORWARD,
    age: 30,
    height: 203,
    weight: 107,
    country: 'США',
    photo: Abromajtiz,
    twitter: 'timabro21',
    instagram: 'timabro',
    images: [],
  },
  {
    id: 8,
    name: 'Андрей Зубков',
    number: 20,
    role: ROLES.FORWARD,
    age: 28,
    height: 205,
    weight: 100,
    country: 'Россия',
    photo: Zubkov,
    twitter: '',
    instagram: 'k1x1k',
    images: [],
  },
  {
    id: 9,
    name: 'Матеуш Понитка',
    number: 25,
    role: ROLES.FORWARD,
    age: 26,
    height: 198,
    weight: 95,
    country: 'Польша',
    photo: Ponitka,
    twitter: '',
    instagram: 'mateuszponitka',
    images: [],
  },
  {
    id: 10,
    name: 'Уилл Томас',
    number: 10,
    role: ROLES.FORWARD,
    age: 33,
    height: 203,
    weight: 104,
    country: 'США',
    photo: Thomas,
    twitter: '',
    instagram: 'thecommonname',
    images: [],
  },
  {
    id: 11,
    name: 'Владислав Трушкин',
    number: 16,
    role: ROLES.FORWARD,
    age: 26,
    height: 201,
    weight: 103,
    country: 'Россия',
    photo: Trushkin,
    twitter: 'vladtrushkin1',
    instagram: 'vlajko11',
    images: [],
  },
  {
    id: 12,
    name: 'Колтон Айверсон',
    number: 4,
    role: ROLES.CENTER,
    age: 30,
    height: 213,
    weight: 116,
    country: 'США',
    photo: Iverson,
    twitter: 'colton_iverson',
    instagram: 'colton_iverson',
    images: [],
  },
  {
    id: 13,
    name: 'Густаво Айон',
    number: 34,
    role: ROLES.CENTER,
    age: 34,
    height: 208,
    weight: 113,
    country: 'Мексика',
    photo: Ayon,
    twitter: 'ayongustavo',
    instagram: 'ayongustavo14',
    images: [],
  },
  {
    id: 14,
    name: 'Антон Пушков',
    number: 14,
    role: ROLES.CENTER,
    age: 30,
    height: 208,
    weight: 100,
    country: 'Россия',
    photo: Pushkov,
    twitter: '',
    instagram: '14push',
    images: [],
  },
];

export default players;
